name: Pre-commit
on:
  pull_request:
  push:
    branches:
      - master
      - spencer-github-action

jobs:
  precommit:
    uses: ./.github/workflows/reusable-precommit.yml
    with:
      BATFISH_GITHUB_BATFISH_REPO: 'batfish/batfish'
      BATFISH_GITHUB_BATFISH_REF: 'master'
      BATFISH_GITHUB_PYBATFISH_REPO: 'batfish/pybatfish'
      BATFISH_GITHUB_PYBATFISH_REF: 'master'
