name: Pre-commit
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 19 * * 1-5'  # 12PM Pacific; M-F
    - cron: '0 0 * * 2-6'   # 5PM Pacific; M-F

jobs:
  precommit:
    uses: ./.github/workflows/reusable-precommit.yml
    with:
      BATFISH_GITHUB_BATFISH_REPO: 'batfish/batfish'
      BATFISH_GITHUB_BATFISH_REF: 'master'
      BATFISH_GITHUB_PYBATFISH_REPO: 'batfish/pybatfish'
      BATFISH_GITHUB_PYBATFISH_REF: 'master'
